#! /usr/bin/bash

# input is $1 = filtered QAPA output
#          $2 = upstream nt
#          $3 = downstream nt
#          $4 = output filename
#
# The PAS generated by QAPA is not the based on BED file, please note
# Need firstly check the PAS of QAPA

# Generate PAS bed style
# From PAS bed to up/down region
# downstream 10bp
# "-" => left-1 , right-1 => left-9
# "+" => left+1 , right+1 => right+9
# upstream 10bp
# "-" => left+1, right+1 => right+9
# "+" => left-1, right-1 => left-9
awk '$8=="+"{print $5"\t"$10-1"\t"$10"\t"$1"_PAS\t0\t"$8}$8=="-"{print $5"\t"$9"\t"$9+1"\t"$1"_PAS\t0\t"$8}' $1 > tmp.PAS.bed

awk '$6=="+"{print $1"\t"$2-'$2'"\t"$3+'$3'"\t"$4"\t"$5"\t"$6}$6=="-"{print $1"\t"$2-'$3'"\t"$3+'$2'"\t"$4"\t"$5"\t"$6}' tmp.PAS.bed > tmp.extractRegion.bed

bedtools getfasta -fi /home/xzx/Work_data/Salt_transcriptome/New_pipeline/APA_analysis/QAPA_pipeline/Gmax_275_v2.0.fa -bed tmp.extractRegion.bed -name+ -s > $4

rm tmp.*
